### ISSUE TITLE
Can't set touchspin value 

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [sjoerd222888/ramTouchSpin#1]
i have some data i get from a web service and set them in a form. with your directive i can't display it in the input. and display it on the view with two-way binding

**Comment by sjoerd222888** [comment]
Can you be more detailed on what you are training to do and what did not work? Have you had a look at the demo file here: https://github.com/sjoerd222888/ramTouchSpin/blob/master/demo/demo.html? The usage is basically the same as with ng-model (it in fact does use ng-model). So just try with a simple input field and ng-model and test whether this works. If this works then the directive should work as well.

**Comment by tiagomsmagalhaes** [comment]
i have set a plnkr and still couldn't set the value or see the output value http://plnkr.co/edit/ICkxbugYEtTJT8soYitQ?p=preview

**Comment by sjoerd222888** [comment]
Please have a look at this: http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model

This is basically a limitation of ng-model and my directive builds on top of ng-model. The value that you use has to be on a model object living in the scope.

**Comment by tiagomsmagalhaes** [comment]
I can use it with this directive and with the normal ng-model. http://plnkr.co/edit/40Bdf61wwg9VR4aACX5i?p=preview the only issue is the spinning while pressing the button.

**Comment by sjoerd222888** [comment]
That is interessting. Thx for posting. I will have a look at this later and try to see what trick they apply to overcome the usual limitation of ng-model.

**Comment by sjoerd222888** [comment]
It should be fixed now. A corresponding example has also been added to the demo file. Please reopen if problem persists.
